/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientcalculatorapplication;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.net.UnknownHostException;

/**
 *
 * @author giova
 */
public class GUICalculator extends javax.swing.JFrame {
    String nome_server="127.0.0.1";
    int porta_server=9999;
    Socket socket;
    String risposta;
    DataOutputStream dati_al_server;
    BufferedReader dati_dal_server;
    /**
     * Creates new form GUICalculator
     */
    public GUICalculator() {
        initComponents();
        connetti();
    }
    public Socket connetti(){
        System.out.println("Client in esecuzione.");
        try {
            socket=new Socket(nome_server,porta_server);
            dati_al_server=new DataOutputStream(socket.getOutputStream());
            dati_dal_server=new BufferedReader(new InputStreamReader(socket.getInputStream()));
        }
        catch(UnknownHostException e){
            System.err.println("Host non riconosciuto.");
        }
        catch (IOException e) {
            System.out.println(e.getMessage());
            System.out.println("Errore durante la connessione.");
            System.exit(1);
        }
        return(socket);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tastierino = new javax.swing.JPanel();
        risultato = new javax.swing.JLabel();
        sette = new javax.swing.JButton();
        otto = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        piu = new javax.swing.JButton();
        quattro = new javax.swing.JButton();
        cinque = new javax.swing.JButton();
        sei = new javax.swing.JButton();
        meno = new javax.swing.JButton();
        uno = new javax.swing.JButton();
        due = new javax.swing.JButton();
        tre = new javax.swing.JButton();
        per = new javax.swing.JButton();
        cancella = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        virgola = new javax.swing.JButton();
        diviso = new javax.swing.JButton();
        calcola = new javax.swing.JButton();
        lastResult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calc...");
        setResizable(false);

        risultato.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        risultato.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        sette.setText("7");
        sette.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setteActionPerformed(evt);
            }
        });

        otto.setText("8");
        otto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ottoActionPerformed(evt);
            }
        });

        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });

        piu.setText("+");
        piu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                piuActionPerformed(evt);
            }
        });

        quattro.setText("4");
        quattro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quattroActionPerformed(evt);
            }
        });

        cinque.setText("5");
        cinque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cinqueActionPerformed(evt);
            }
        });

        sei.setText("6");
        sei.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seiActionPerformed(evt);
            }
        });

        meno.setText("-");
        meno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menoActionPerformed(evt);
            }
        });

        uno.setText("1");
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });

        due.setText("2");
        due.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dueActionPerformed(evt);
            }
        });

        tre.setText("3");
        tre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treActionPerformed(evt);
            }
        });

        per.setText("x");
        per.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perActionPerformed(evt);
            }
        });

        cancella.setText("C");
        cancella.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancellaActionPerformed(evt);
            }
        });

        zero.setText("0");
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        virgola.setText(".");
        virgola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                virgolaActionPerformed(evt);
            }
        });

        diviso.setText(":");
        diviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisoActionPerformed(evt);
            }
        });

        calcola.setText("Calcola");
        calcola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcolaActionPerformed(evt);
            }
        });

        lastResult.setText("LR");
        lastResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastResultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tastierinoLayout = new javax.swing.GroupLayout(tastierino);
        tastierino.setLayout(tastierinoLayout);
        tastierinoLayout.setHorizontalGroup(
            tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tastierinoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(tastierinoLayout.createSequentialGroup()
                        .addComponent(sette, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(piu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tastierinoLayout.createSequentialGroup()
                        .addComponent(quattro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cinque, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sei, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(meno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tastierinoLayout.createSequentialGroup()
                        .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(due, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tastierinoLayout.createSequentialGroup()
                        .addGroup(tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(calcola, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tastierinoLayout.createSequentialGroup()
                                .addComponent(cancella, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(virgola, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diviso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(risultato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tastierinoLayout.setVerticalGroup(
            tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tastierinoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(risultato, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sette, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(otto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nove, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(piu, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quattro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cinque, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sei, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(due, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tre, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(per, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancella, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(virgola, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diviso, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tastierinoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calcola, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastResult, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tastierino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tastierino, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        risultato.setText(risultato.getText()+"0");
    }//GEN-LAST:event_zeroActionPerformed

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        risultato.setText(risultato.getText()+"1");
    }//GEN-LAST:event_unoActionPerformed

    private void dueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dueActionPerformed
        risultato.setText(risultato.getText()+"2");
    }//GEN-LAST:event_dueActionPerformed

    private void treActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treActionPerformed
        risultato.setText(risultato.getText()+"3");
    }//GEN-LAST:event_treActionPerformed

    private void quattroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quattroActionPerformed
        risultato.setText(risultato.getText()+"4");
    }//GEN-LAST:event_quattroActionPerformed

    private void cinqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cinqueActionPerformed
        risultato.setText(risultato.getText()+"5");
    }//GEN-LAST:event_cinqueActionPerformed

    private void seiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seiActionPerformed
        risultato.setText(risultato.getText()+"6");
    }//GEN-LAST:event_seiActionPerformed

    private void setteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setteActionPerformed
        risultato.setText(risultato.getText()+"7");
    }//GEN-LAST:event_setteActionPerformed

    private void ottoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ottoActionPerformed
        risultato.setText(risultato.getText()+"8");
    }//GEN-LAST:event_ottoActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        risultato.setText(risultato.getText()+"9");
    }//GEN-LAST:event_noveActionPerformed

    private void piuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_piuActionPerformed
        risultato.setText(risultato.getText()+"+");
    }//GEN-LAST:event_piuActionPerformed

    private void menoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menoActionPerformed
        risultato.setText(risultato.getText()+"-");
    }//GEN-LAST:event_menoActionPerformed

    private void perActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perActionPerformed
        risultato.setText(risultato.getText()+"*");
    }//GEN-LAST:event_perActionPerformed

    private void divisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisoActionPerformed
        risultato.setText(risultato.getText()+"/");
    }//GEN-LAST:event_divisoActionPerformed

    private void cancellaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancellaActionPerformed
        risultato.setText("");
    }//GEN-LAST:event_cancellaActionPerformed

    private void lastResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastResultActionPerformed
        risultato.setText(risultato.getText()+"ris");
    }//GEN-LAST:event_lastResultActionPerformed

    private void virgolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_virgolaActionPerformed
        risultato.setText(risultato.getText()+".");
    }//GEN-LAST:event_virgolaActionPerformed

    private void calcolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcolaActionPerformed
        try {
            System.out.println("Invio del messaggio al server.");
            dati_al_server.writeBytes(risultato.getText()+'\n');
            System.out.println("In attesa di risposta dal server.");
            risposta=dati_dal_server.readLine();
            risultato.setText(risposta);
        }
        catch (IOException e) {
            System.out.println(e.getMessage());
            System.out.println("Errore durante la comunicazione col server.");
            System.exit(1);
        }
    }//GEN-LAST:event_calcolaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calcola;
    private javax.swing.JButton cancella;
    private javax.swing.JButton cinque;
    private javax.swing.JButton diviso;
    private javax.swing.JButton due;
    private javax.swing.JButton lastResult;
    private javax.swing.JButton meno;
    private javax.swing.JButton nove;
    private javax.swing.JButton otto;
    private javax.swing.JButton per;
    private javax.swing.JButton piu;
    private javax.swing.JButton quattro;
    private javax.swing.JLabel risultato;
    private javax.swing.JButton sei;
    private javax.swing.JButton sette;
    private javax.swing.JPanel tastierino;
    private javax.swing.JButton tre;
    private javax.swing.JButton uno;
    private javax.swing.JButton virgola;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
